### PR TITLE
fix: upgrade clusterset clustersetbinding to v1beta2

### LINKED ISSUE #80: Upgrade ClusterSet and ClusterSetBinding API usage to v1beta2
Upgrade resources version for all files under:

https://github.com/open-cluster-management-io/ocm-vscode-extension/blob/4ef114e13e23022503788ee1c7c13885a78690f7/templates/Git

### PR DESCRIPTION
**Pull request by haoqing0110**
Refer to https://github.com/open-cluster-management-io/api/pull/266, the ClusterSet ClusterSetBinding API version v1beta1 has been removed, need to upgrade the API to v1beta2. 

Screenshot 2023-10-25 at 17 31 22

```
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSet
metadata:
  name: clusterset-test
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: clusterset-test # should be identical to the underlying ManagedClusterSet
  namespace: clusterset-test-ns
spec:
  clusterSet: clusterset-test
```
```
➜  test-workspace git:(br_clusterset-v1beta2) kubectl create -f mcs.yaml 
managedclusterset.cluster.open-cluster-management.io/clusterset-test created
managedclustersetbinding.cluster.open-cluster-management.io/clusterset-test created

➜  test-workspace git:(br_clusterset-v1beta2) kubectl get managedclusterset clusterset-test -oyaml
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSet
metadata:
  creationTimestamp: "2023-10-25T09:27:40Z"
  generation: 1
  name: clusterset-test
  resourceVersion: "646001"
  uid: 328fd86b-3270-47ec-985f-71af31f90620
spec:
  clusterSelector:
    selectorType: ExclusiveClusterSetLabel
status:
  conditions:
  - lastTransitionTime: "2023-10-25T09:27:40Z"
    message: No ManagedCluster selected
    reason: NoClusterMatched
    status: "True"
    type: ClusterSetEmpty

➜  test-workspace git:(br_clusterset-v1beta2) kubectl get managedclustersetbinding -n clusterset-test-ns clusterset-test -oyaml
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  creationTimestamp: "2023-10-25T09:27:40Z"
  generation: 1
  name: clusterset-test
  namespace: clusterset-test-ns
  resourceVersion: "646003"
  uid: 6840b2fb-cada-4dd6-ae5c-d35637094fad
spec:
  clusterSet: clusterset-test
status:
  conditions:
  - lastTransitionTime: "2023-10-25T09:27:40Z"
    message: ""
    reason: ClusterSetBound
    status: "True"
    type: Bound
```

### CODE REVIEW

**Comment by ilan-pinto** [comment]
@haoqing0110 it seems that you only changed the API version without modifying other fields, is that the case? 
have you tested it. to confirm ?

**Comment by haoqing0110** [comment]
Hello @ilan-pinto it looks like the *.json files I'm updating only have a spec.clusterSet field defined, this part does not change in v1beta2. I have tested the code with vscode debug, not sure if more testing needed?

**Comment by ilan-pinto** [comment]
@haoqing0110 try to apply it on a local cluster to confirm

**Comment by haoqing0110** [comment]
@ilan-pinto thanks for providing some comments, plz see my testing result in the above, the v1beta2 works.

**Comment by haoqing0110** [comment]
hello @ilan-pinto , could you help to tag this PR?

**Comment by TomerFi** [comment]
@haoqing0110 Sorry for the delay; I will take a look at this by the end of the week.

**Comment by TomerFi** [comment]
@haoqing0110 Thank you very much! I apologize for the delays.

**Comment by TomerFi** [comment]
Releasing is currently blocked, fixed in https://github.com/open-cluster-management-io/ocm-vscode-extension/pull/82.

**Comment by TomerFi** [comment]
Finally, [early-access version](https://github.com/open-cluster-management-io/ocm-vscode-extension/releases/tag/early-access) released.
I'll release full version tomorrow.

**Comment by TomerFi** [comment]
Sorry for the delay, we had an issue with our api key and I missed a message with our new one.
All is working now, version [1.3.0](https://github.com/open-cluster-management-io/ocm-vscode-extension/releases/tag/1.3.0) released.

**Pull request merged**
